# Generated by Django 5.0.1 on 2024-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('destination_type', models.CharField(choices=[('adventure', 'Adventure'), ('family', 'Family'), ('business', 'Business'), ('cultural', 'Cultural'), ('leisure', 'Leisure')], max_length=50)),
                ('popular_activities', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/')),
            ],
        ),
    ]
