# Generated by Django 5.0.1 on 2024-02-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('leisure', 'Leisure'), ('sport', 'Sport'), ('educational', 'Educational')], max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travelapp.destination')),
            ],
        ),
    ]
