# Generated by Django 5.0.1 on 2024-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_destination_amenities_destination_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='price_per_adult',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='price_per_child',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=6),
            preserve_default=False,
        ),
    ]
