# Generated by Django 5.0.1 on 2024-03-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_activity_location_activity_price_per_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='travelapp.booking'),
        ),
    ]
