# Generated by Django 5.0.1 on 2024-03-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='travelapp.booking'),
        ),
    ]
