# Generated by Django 5.0.1 on 2024-03-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_transfer_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.AddField(
            model_name='checklist',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='travelapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='travelapp.userprofile'),
            preserve_default=False,
        ),
    ]
