# Generated by Django 5.0.1 on 2024-03-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_remove_checklist_user_remove_transfer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='travelapp.activity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='travelapp.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('activity', 'Activity'), ('transfer', 'Transfer'), ('destination', 'Destination')], max_length=50),
        ),
    ]
