# Generated by Django 5.0.1 on 2024-04-05 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_booking_activity_booking_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('city', 'City'), ('country', 'Country'), ('region', 'Region')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amenities', models.JSONField(default=list)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodation_images/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='travelapp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=255)),
                ('departure_airport', models.CharField(max_length=255)),
                ('arrival_airport', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='travelapp.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
