name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:


  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: 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
      DOCKER_TOKEN: dckr_pat_fSO3010DSsk47dvmK5VTtxP8ZSM
      DEPLOYMENT_REPO: nixswinner/argocd-deployments #owner/private-repo

    steps:
    - uses: actions/checkout@v3
    - name: Get short commit hash
      id: get_commit_hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}

    - name: Log in to Docker Hub
      run: docker login -u nixswinner -p ${{ env.DOCKER_TOKEN }}
      
    - name: Push Docker image
      run: docker push nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}
      
    - name: Checkout Deployment repo
      uses: actions/checkout@v2
      with:
        repository: ${{ env.DEPLOYMENT_REPO }}
        token: ${{ env.GITHUB_TOKEN }}

    - name: Make Image Update Deployment file
      run: |
        git config user.name "ZiaraSystem Deployment Bot"
        git config user.email "bot@nixswinner.com"
        
        sed -i 's|image: nixswinner/ziara-server:[^ ]*|image: nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}|' ziara/ziara-deploy-svc.yaml

        git add .
        git commit -m "Update image nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}"
        git push

