name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:
  env:
    GITHUB_TOKEN: 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
    DOCKER_TOKEN: dckr_pat_fSO3010DSsk47dvmK5VTtxP8ZSM

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get short commit hash
      id: get_commit_hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}

    - name: Log in to Docker Hub
      run: docker login -u nixswinner -p ${{ env.DOCKER_TOKEN }}
      
    - name: Push Docker image
      run: docker push nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}
    - name: Update Deployment Manifest
      run: |
        curl -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o ziara-deploy-svc.yaml \
             https://raw.githubusercontent.com/nixswinner/argocd-deployments/main/ziara/ziara-deploy-svc.yaml

        sed -i 's|image: nixswinner/ziara-server:.*$|image: nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}|' ziara-deploy-svc.yaml

        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ziara-deploy-svc.yaml
        git commit -m "Update image in ziara-deploy-svc.yaml to latest"
        git push
