name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get short commit hash
      id: get_commit_hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ziara-server:${{ steps.get_commit_hash.outputs.hash }}

    - name: Log in to Docker Hub
      run: docker login -u nixswinner -p dckr_pat_fSO3010DSsk47dvmK5VTtxP8ZSM
      
    - name: Push Docker image
      run: docker push nixswinner/ziara-server:${{ steps.get_commit_hash.outputs.hash }}

